
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app
data:
  APP_PORT: "5000"
  NODE_ENV: "production"
  DB_HOST: "postgres"          # k8s Service name for postgres, DNS-resolvable in-cluster
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "appdb"
  PGADMIN_DEFAULT_EMAIL: "admin@example.com"
  PGADMIN_PORT: "80"
 